# Generated by Django 3.2.20 on 2023-09-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='type',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
