# Generated by Django 3.2.20 on 2023-09-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_comida_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='imgUrl',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
