# Generated by Django 3.2.20 on 2023-09-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_comida_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
